### ISSUE TITLE
Indicate which entries do what they do best, where appropriate

### ISSUE THREAD

**Issue by Ortham** [Ortham/buddah#3]
There are a lot of entries that do pretty much exactly the same thing, and they are not all equal: some are at very early stages, some are very feature-rich, and there should be some indication of this: there's no point working off library X if library Y does the same thing but better.

**Comment by Scrivener07** [comment]
Sometimes there is a point in working with a lesser library when Y does it better. There are times when the better library is not an option because a project may have certain requirements which vary with whatever is being worked on. I think I just have a problem with the word "best". A better way to look at it would be as a curated "this is probably what your looking for". Even that is only half the problem. You need a way to  determine the exact **context of what** a user is looking for in order to say an entry is "probably what your looking for". 

So my question is how will you determine what the user is looking for to say an entry is the best?

Here is a story to show another perspective. I was working on some skyrim UI project and hopped onto an actionscript forum to get some AS2 help. The solution I got was to use AS3 as it would be much easier to accomplish than with AS2. Of course I couldnt use the **best** library because I had a project requirement of AS2.

These are just some thoughts to consider in your design.

**Comment by Ortham** [comment]
Yeah, those kinds of problems are why I haven't done anything about this yet. I'll just close it, because I haven't come up with a good solution.
